version: '3.8'
services:
    front:
      build: ./front
      ports:
        - "3000:3000"
      container_name: front
      stdin_open: true
      volumes:
        - ./front:/usr/src/app/front
      depends_on:
        - app
    app:
      container_name: springboot-postgresql
      image: springboot-postgresql
      restart: always
      build: ./
      ports:
        - "8443:8443"
      depends_on:
        - postgres
    postgres:
        image: postgres:15.1
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5458:5432'
        volumes:
          - ./docker/postgres-data:/var/lib/postgresql/data
          - ./docker/sql/postgres_localhost-2023_01_14_00_23_52-dump.sql.gz:/docker-entrypoint-initdb.d/postgres_localhost-2023_01_14_00_23_52-dump.sql.gz
